### ISSUE TITLE
Create a horizontal ORStackView

### ISSUE THREAD

**Issue by dblock** [orta/ORStackView#10]
I'd like to stack things horizontally. That's a bit of an oxymoron, "stack" horizontally.

**Comment by garnett** [comment]
I want to take this one. At first I thought to keep it simple and just introduce ```direction``` property, but there are methods in public API that explicitly say about used direction (like ```addSubview:withTopMargin``` or ```insertSubview:belowSubview```), logical output of this observation is to 
- have shared ```internal class``` ```GenericStackView``` and two sibilings ```ORStackView``` and ```ORHorizontalStackView```.
- try to avoid base class and use some composition here.

**Comment by dblock** [comment]
@garnett :+1:

**Comment by orta** [comment]
I think that's a good way to do it @garnett :+1: - please ensure it has tests too

**Comment by garnett** [comment]
@orta but which one of the two I've described? :smile:

**Comment by orta** [comment]
Hah - sorry, I originally thought about the internal class, but I think I'm more open to the composition. 

The biggest problem lies in that `ORTagBasedAutoStackView` ideally would want to fit in this too. Perhaps there could be a base class that has a layout class like structure. Similar in metaphor to UICollectionView with the UICollectionViewLayout object?

**Comment by garnett** [comment]
Yes that makes sense, I will think about it and update the ticket with high level concept.

**Comment by orta** [comment]
:+1:
