### ISSUE TITLE
Layout in the example is not working in iOS 8

### ISSUE THREAD

**Issue by dbgrandi** [orta/ORStackView#22]
This has also affected the specs. Of the 5 tabs, the last 2 (which have a UIView as the root view) look fine, the first 3 are squished like this...

![orstackviewexample](https://cloud.githubusercontent.com/assets/4033/4568416/0a622c66-4f3a-11e4-9d07-ab353f759955.png)

I can make a PR for this, just wanted to log the issue.

**Comment by orta** [comment]
This got fixed.
