### ISSUE TITLE
Change margin type from NSString * to CGFloat?

### ISSUE THREAD

**Issue by garnett** [orta/ORStackView#25]
I haven't seen the use case when real predicate was passed to margin param + it looks like exposing implementation details of ```FLKAutoLayout```.

I can make PR if this works for you, @orta 

UPD: there are ```predicates``` in split view, but they should not be affected though

**Comment by orta** [comment]
I did a quick audit of the [eigen](https://github.com/artsy/eigen/) codebase, we have 1 use where it is not just a number, I think this is fine. It's a major breaking change, so we'd need to bump the major SemVer, but that's totally reasonable IMO.

**Comment by garnett** [comment]
:+1:
