### ISSUE TITLE
Support for UIWebView

### ISSUE THREAD

**Issue by iferrera** [orta/ORStackView#34]
Hello!

I'm facing problems when trying to add a UIWebView into the stackview. There's no way to see it, even if I add it before of loading the HTML, or after.

Does ORStackView support UIWebView? 
Which steps should I do in order to make it work?

Thanks!

**Comment by orta** [comment]
It should support a UIWebView just fine to my knowledge, it would have no intrinsic height/width, so you would need to set those yourself. I don't think we have any code that does this though, so I could be wrong.

**Comment by iferrera** [comment]
Ok, managed to solve it by subclassing UIWebView and setting the intrinsic content size after the UIWebview loads its content.

Thanks for the hint. You can close this if you want.
