### ISSUE TITLE
Nested ORStackView with different orientation

### ISSUE THREAD

**Issue by bradphilips** [orta/ORStackView#35]
@orta It seems if i have a nested `ORStackView` with a different orientation (`.Vertical` vs `.Horizontal`) it always constrains this at the top of the view:

Example:
```Swift
class MainViewController: ORStackViewController {
...

    override func viewDidLoad() {
        self.stackView.direction = .Vertical
        ... add a ton of views here
        let otherStackView = ORStackView(frame: CGRectZero)
        otherStackView.direction = .Horizontal
        otherStackView.addSubview(someOtherView, withPrecedingMargin: 20)
        stackView.addSubView(otherStackView, withPrecedingMargin: 0) //Always at the top of the view
```

Is a nested `ORStackView` supported and if so, in different orientations?  It seems just fine if I nest one in the same orientation.  Let me know.  Thanks!

**Comment by orta** [comment]
We nest StackViews all the time in Artsy apps, we've not migrated to the API that supports horizontal stacks, but offhand I can't think of a reason why they wouldn't work

![screen shot 2015-11-13 at 3 33 59 pm](https://cloud.githubusercontent.com/assets/49038/11156806/10e2643e-8a1c-11e5-9021-0ab18b3ad207.png)

**Comment by bradphilips** [comment]
Hey @orta, I figured this out.  Looks like if you don't specify a `sideMargin` even if its 0 when adding views to the nested stackview it would align it to the top.  Probably something with how my view is configured.  Thanks for your help.

**Comment by orta** [comment]
Thank you for coming back with the answer!
